import {
  ShoppingBag,
  Trash2,
  User,
  LogIn,
  LogOut,
  ChevronLeft,
  ChevronRight,
  X,
  Heart,
  CheckCircle,
  AlertCircle,
  Plus,
  List,
  ArrowLeft,
  ArrowRight,
  MapPin,
} from "lucide-react";

export const Icons = {
  plus: Plus,
  cart: ShoppingBag,
  trash: Trash2,
  user: User,
  login: LogIn,
  logout: LogOut,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  close: X,
  wishlist: Heart,
  success: CheckCircle,
  error: AlertCircle,
  list: List,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  mapPin: MapPin,
};
